# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:53:57+00:00

from __future__ import annotations

from typing import List

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, conint, constr


class OBEventLink1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    link: str = Field(..., description='Resource link.')
    version: constr(min_length=1, max_length=10) = Field(
        ..., description='Resource version.'
    )


class OBEventSubject1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    http___openbanking_org_uk_rid: constr(min_length=1, max_length=128) = Field(
        ...,
        alias='http://openbanking.org.uk/rid',
        description='Resource Id for the updated resource.',
    )
    http___openbanking_org_uk_rlk: List[OBEventLink1] = Field(
        ...,
        alias='http://openbanking.org.uk/rlk',
        description='Resource links to other available versions of the resource.',
        min_length=1,
    )
    http___openbanking_org_uk_rty: constr(min_length=1, max_length=128) = Field(
        ...,
        alias='http://openbanking.org.uk/rty',
        description='Resource Type for the updated resource.',
    )
    subject_type: constr(min_length=1, max_length=128) = Field(
        ..., description='Subject type for the updated resource. '
    )


class OBEventResourceUpdate1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: OBEventSubject1


class OBEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    urn_uk_org_openbanking_events_resource_update: OBEventResourceUpdate1 = Field(
        ..., alias='urn:uk:org:openbanking:events:resource-update'
    )


class OBEventNotification1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aud: constr(min_length=1, max_length=128) = Field(..., description='Audience.')
    events: OBEvent1
    iat: conint(ge=0) = Field(..., description='Issued At. ')
    iss: str = Field(..., description='Issuer.')
    jti: constr(min_length=1, max_length=128) = Field(..., description='JWT ID.')
    sub: AnyUrl = Field(..., description='Subject')
    toe: conint(ge=0) = Field(..., description='Time of Event.')
    txn: constr(min_length=1, max_length=128) = Field(
        ..., description='Transaction Identifier.'
    )
